runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: posts/index.html
    upload: posts/index.html
  - url: /
    static_dir: posts

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE